<?php
/** @var array $order */ /** @var array $budget */
?>
<?php if (!empty($order['work_location_type'])): ?><div class="glass-card p-4 mb-3"><div class="small"><span class="text-secondary d-block">Work Location / Service Area</span><?= !empty($order['maintenance_category']) ? e($order['maintenance_category']) . ' · ' : '' ?><?= e($order['work_location_name'] ?? 'No records available.') ?></div></div><?php endif; ?>
<div class="page-head"><div><h1 class="page-title">Purchase Order</h1><span class="page-sub">Read-only details for <?= e($order['po_no']) ?></span></div><div><a class="btn btn-outline-secondary btn-sm" target="_blank" href="<?= e(base_url('purchase-orders/' . $order['id'] . '/print')) ?>">PDF / Print</a> <a class="btn btn-outline-secondary btn-sm" href="<?= e(base_url('api/purchase-orders/export?format=excel&id=' . $order['id'])) ?>">Excel</a> <a class="btn btn-outline-secondary btn-sm" href="<?= e(base_url('purchase-orders')) ?>"><i class="fa-solid fa-arrow-left me-1"></i> Back</a></div></div>

<div class="glass-card p-4 mb-3"><div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><div class="text-secondary small">Purchase Order Number</div><h4 class="mb-0 text-primary"><?= e($order['po_no']) ?></h4></div><span class="badge text-bg-secondary text-capitalize"><?= e($order['status']) ?></span></div><div class="row g-3 small"><div class="col-md-4"><span class="text-secondary d-block">Department</span><?= e($order['department_name']) ?></div><div class="col-md-4"><span class="text-secondary d-block">Financial Year</span><?= e($order['financial_year']) ?></div><div class="col-md-4"><span class="text-secondary d-block">Linked Request</span><?= e($order['pr_no'] ?? 'No records available.') ?></div><div class="col-md-4"><span class="text-secondary d-block">Vendor</span><?= e($order['vendor_name']) ?></div><div class="col-md-4"><span class="text-secondary d-block">Invoice Number</span><?= e($order['invoice_no'] ?? 'No records available.') ?></div><div class="col-md-4"><span class="text-secondary d-block">Requested Amount</span><strong><?= money((float) $order['total_amount']) ?></strong></div><div class="col-12"><span class="text-secondary d-block">Vendor Address</span><?= $order['vendor_address'] ? nl2br(e($order['vendor_address'])) : '<span class="text-secondary">No records available.</span>' ?></div><div class="col-12"><span class="text-secondary d-block">Previous Remarks</span><?= $order['remarks'] ? nl2br(e($order['remarks'])) : '<span class="text-secondary">No records available.</span>' ?></div></div></div>

<div class="glass-card p-4 mb-3"><h5 class="mb-3">Budget Details</h5><?php if ($budget['has_budget']): ?><div class="row g-3 small"><div class="col-6 col-md-3"><span class="text-secondary d-block">Allocated</span><?= money($budget['allocated']) ?></div><div class="col-6 col-md-3"><span class="text-secondary d-block">Committed</span><?= money($budget['committed']) ?></div><div class="col-6 col-md-3"><span class="text-secondary d-block">Used</span><?= money($budget['used']) ?></div><div class="col-6 col-md-3"><span class="text-secondary d-block">Remaining Budget</span><strong><?= money($budget['available']) ?></strong></div></div><?php else: ?><span class="text-secondary small">No records available.</span><?php endif; ?></div>

<div class="glass-card p-4 mb-3"><h5 class="mb-3">Order Items</h5><?php if ($order['items'] === []): ?><span class="text-secondary small">No records available.</span><?php else: ?><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Item</th><th>Description</th><th class="text-end">Quantity</th><th class="text-end">Unit Price</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach ($order['items'] as $item): ?><tr><td><?= e($item['item_name']) ?></td><td><?= e($item['description'] ?? '—') ?></td><td class="text-end"><?= e($item['quantity']) ?></td><td class="text-end"><?= money((float) $item['unit_price']) ?></td><td class="text-end"><?= money((float) $item['amount']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><div class="small text-end mt-3">Subtotal: <?= money((float) $order['subtotal']) ?> · GST (<?= e($order['gst_percent']) ?>%): <?= money((float) $order['gst_amount']) ?> · <strong>Total: <?= money((float) $order['total_amount']) ?></strong></div></div>

<div class="glass-card p-4 mb-3"><h5 class="mb-3">Attachments</h5><span class="text-secondary small">No attachments.</span></div>
<div class="glass-card p-4"><h5 class="mb-3">Approval / Status History</h5><?php if ($order['history'] === []): ?><span class="text-secondary small">No records available.</span><?php else: ?><div class="small"><?php foreach ($order['history'] as $entry): ?><div class="mb-2"><strong class="text-capitalize"><?= e($entry['status']) ?></strong><span class="text-secondary ms-2"><?= e($entry['changed_by_name'] ?? 'System') ?> · <?= e($entry['created_at']) ?></span><?= $entry['remarks'] ? '<div class="text-secondary mt-1">' . nl2br(e($entry['remarks'])) . '</div>' : '' ?></div><?php endforeach; ?></div><?php endif; ?></div>
